In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib

from datetime import datetime



from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (precision_score, recall_score, f1_score, make_scorer,
                             accuracy_score, classification_report, confusion_matrix)


from sklearn.preprocessing import StandardScaler, MinMaxScaler

# SMOTEENN

from imblearn.combine import SMOTEENN
from imblearn.over_sampling import SMOTE, ADASYN

from xgboost import XGBClassifier
from collections import Counter

from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

import optuna
from sklearn.model_selection import cross_val_score

c:\Projects\Customer_churn\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = pd.read_csv("..//data//raw//Customer-Churn.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.Churn.value_counts() / len(df) * 100

Churn
No     73.463013
Yes    26.536987
Name: count, dtype: float64

## Churn rate is 26.53 %

In [5]:
X = df.drop(columns= ['Churn', 'customerID'])

y = df.Churn

print("Shape of X : " , X.shape)
print("Shape of y : ", y.shape)

Shape of X :  (7043, 19)
Shape of y :  (7043,)

In [6]:
X = pd.get_dummies(X, drop_first= True)

y = df.Churn.map({'No' : 0, 'Yes' : 1})

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,stratify=y, random_state=42)

In [8]:
len(X_train)

5634

In [9]:
len(X_test)

1409

In [10]:
experiment_results = []


def log_experiment(
    model_name,
    approach,
    y_true,
    y_pred,
    cv_f1=None,
    best_params=None,
    notes=None
):
    """
    Store model evaluation results in a central list.
    """

    result = {
    "Model": model_name,
    "Approach": approach,
    "Accuracy": accuracy_score(y_true, y_pred),
    "Precision": precision_score(y_true, y_pred, zero_division=0),
    "Recall": recall_score(y_true, y_pred, zero_division=0),
    "F1": f1_score(y_true, y_pred, zero_division=0),
    "CV_F1_Mean": cv_f1,
    "Best_Params": str(best_params) if best_params else None,
    "Notes": notes
}

    experiment_results.append(result)

    return pd.DataFrame(experiment_results)

In [11]:
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [12]:
y_pred_dt = model_dt.predict(X_test)

In [13]:
log_experiment(
    model_name="DecisionTree",
    approach="Baseline",
    y_true=y_test,
    y_pred=y_pred_dt,
    notes="Base line Decision Tree model"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.56875,0.486631,0.524496,None,None,Base line Decision Tree model

In [14]:
print(classification_report(y_true=y_test, y_pred=y_pred_dt))

              precision    recall  f1-score   support

           0       0.82      0.87      0.84      1035
           1       0.57      0.49      0.52       374

    accuracy                           0.77      1409
   macro avg       0.70      0.68      0.68      1409
weighted avg       0.76      0.77      0.76      1409

In [15]:
### Base model has an accuracy of 77 %

In [16]:
# Data Cleaning
teleco_data = df.copy()

In [17]:
teleco_data.TotalCharges = pd.to_numeric(teleco_data.TotalCharges, errors='coerce')

In [18]:
teleco_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [19]:
teleco_data.loc[teleco_data.TotalCharges.isnull() == True]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [20]:
teleco_data.dropna(how='any', inplace=True)

In [21]:
teleco_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [22]:
bins = [0,12,24,36,48, 60, 72]

labels = ['1-12', '13-24', '25-36', '37-48', '49-60', '61-72']

teleco_data['tenure_bin'] = pd.cut(teleco_data.tenure, bins=bins, labels=labels, include_lowest=True)

print(teleco_data[['tenure', 'tenure_bin']].head())
print(teleco_data.tenure_bin.value_counts().sort_index())

   tenure tenure_bin
0       1       1-12
1      34      25-36
2       2       1-12
3      45      37-48
4       2       1-12
tenure_bin
1-12     2175
13-24    1024
25-36     832
37-48     762
49-60     832
61-72    1407
Name: count, dtype: int64

In [23]:
teleco_data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_bin
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1-12
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,25-36
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1-12
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,37-48
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1-12

In [24]:
teleco_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
 21  tenure_bin        7032 non-null   category
dtypes: category(1), float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [25]:
X = teleco_data.drop(columns= ['Churn', 'customerID', 'tenure'])

y = teleco_data.Churn

print("Shape of X : " , X.shape)
print("Shape of y : ", y.shape)

Shape of X :  (7032, 19)
Shape of y :  (7032,)

In [26]:
X = pd.get_dummies(X, drop_first= True)

y = teleco_data.Churn.map({'No' : 0, 'Yes' : 1})

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [28]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [29]:
model_dt2 = DecisionTreeClassifier()
model_dt2.fit(X_train, y_train)

y_pred_dt2 = model_dt2.predict(X_test)

In [30]:
log_experiment(
    model_name="DecisionTree",
    approach="StandardScaler",
    y_true=y_test,
    y_pred=y_pred_dt2,
    notes="Decision Tree after Standard Scaler"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler

In [31]:
print(classification_report(y_pred=y_pred_dt2, y_true=y_test))

              precision    recall  f1-score   support

           0       0.81      0.78      0.80      1033
           1       0.45      0.49      0.47       374

    accuracy                           0.71      1407
   macro avg       0.63      0.64      0.63      1407
weighted avg       0.71      0.71      0.71      1407

In [32]:
mms = MinMaxScaler()
X_train_mms = mms.fit_transform(X_train)
X_test_mms = mms.transform(X_test)

In [33]:
model_dt3 = DecisionTreeClassifier()
model_dt3.fit(X_train_mms, y_train)

y_pred_dt3 = model_dt3.predict(X_test_mms)

In [34]:
log_experiment(
    model_name="DecisionTree",
    approach="MinMaxScaler",
    y_true=y_test,
    y_pred=y_pred_dt3,
    notes="Decision Tree with Min Max"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler
2,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max

In [35]:
print(classification_report(y_pred=y_pred_dt3, y_true=y_test))

              precision    recall  f1-score   support

           0       0.82      0.79      0.80      1033
           1       0.47      0.51      0.49       374

    accuracy                           0.71      1407
   macro avg       0.64      0.65      0.65      1407
weighted avg       0.72      0.71      0.72      1407

In [36]:
sm = SMOTEENN()
X_train_resampled, y_train_resampled = sm.fit_resample(X_train, y_train)

In [37]:
model_dt_smoteenn = DecisionTreeClassifier()
model_dt_smoteenn.fit(X_train_resampled, y_train_resampled)

y_pred_dt_smoteenn = model_dt_smoteenn.predict(X_test)

In [38]:
log_experiment(
    model_name="DecisionTree",
    approach="SMOTEENN",
    y_true=y_test,
    y_pred=y_pred_dt_smoteenn,
    notes="Decision Tree with smoteenn"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler
2,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max
3,DecisionTree,SMOTEENN,0.725657,0.489691,0.762032,0.596234,None,None,Decision Tree with smoteenn

In [39]:
print(classification_report(y_pred=y_pred_dt_smoteenn, y_true=y_test))

              precision    recall  f1-score   support

           0       0.89      0.71      0.79      1033
           1       0.49      0.76      0.60       374

    accuracy                           0.73      1407
   macro avg       0.69      0.74      0.69      1407
weighted avg       0.79      0.73      0.74      1407

In [40]:
model_rf_smoteenn = RandomForestClassifier(n_estimators=500)
model_rf_smoteenn.fit(X_train_resampled, y_train_resampled)

y_pred_rf_smoteenn = model_rf_smoteenn.predict(X_test)

In [41]:
log_experiment(
    model_name="RandomForest",
    approach="SMOTEENN",
    y_true=y_test,
    y_pred=y_pred_rf_smoteenn,
    notes="Random Forest + SMOTEENN"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler
2,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max
3,DecisionTree,SMOTEENN,0.725657,0.489691,0.762032,0.596234,None,None,Decision Tree with smoteenn
4,RandomForest,SMOTEENN,0.718550,0.482026,0.788770,0.598377,None,None,Random Forest + SMOTEENN

In [42]:
print(classification_report(y_pred=y_pred_rf_smoteenn, y_true=y_test))

              precision    recall  f1-score   support

           0       0.90      0.69      0.78      1033
           1       0.48      0.79      0.60       374

    accuracy                           0.72      1407
   macro avg       0.69      0.74      0.69      1407
weighted avg       0.79      0.72      0.73      1407

In [43]:
model_xgb = XGBClassifier(random_state = 42)
model_xgb.fit(X_train, y_train)

y_pred_xgb = model_xgb.predict(X_test)

In [44]:
log_experiment(
    model_name="XGBoost",
    approach="Baseline",
    y_true=y_test,
    y_pred=y_pred_xgb,
    notes="Default XGBoost parameters"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler
2,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max
3,DecisionTree,SMOTEENN,0.725657,0.489691,0.762032,0.596234,None,None,Decision Tree with smoteenn
4,RandomForest,SMOTEENN,0.718550,0.482026,0.788770,0.598377,None,None,Random Forest + SMOTEENN
5,XGBoost,Baseline,0.769723,0.572254,0.529412,0.550000,None,None,Default XGBoost parameters

In [45]:
print(classification_report(y_pred=y_pred_xgb, y_true=y_test))

              precision    recall  f1-score   support

           0       0.83      0.86      0.85      1033
           1       0.57      0.53      0.55       374

    accuracy                           0.77      1407
   macro avg       0.70      0.69      0.70      1407
weighted avg       0.76      0.77      0.77      1407

In [46]:
model_xgb_smoteenn = XGBClassifier(random_state = 42)
model_xgb_smoteenn.fit(X_train_resampled, y_train_resampled)

y_pred_xgb_smoteenn = model_xgb_smoteenn.predict(X_test)

print(classification_report(y_pred=y_pred_xgb_smoteenn, y_true=y_test))

              precision    recall  f1-score   support

           0       0.90      0.71      0.80      1033
           1       0.50      0.79      0.61       374

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.79      0.73      0.75      1407

In [47]:
log_experiment(
    model_name="XGBoost",
    approach="SMOTEENN",
    y_true=y_test,
    y_pred=y_pred_xgb_smoteenn,
    notes="XGBoost parameters with somte enn"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler
2,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max
3,DecisionTree,SMOTEENN,0.725657,0.489691,0.762032,0.596234,None,None,Decision Tree with smoteenn
4,RandomForest,SMOTEENN,0.718550,0.482026,0.788770,0.598377,None,None,Random Forest + SMOTEENN
5,XGBoost,Baseline,0.769723,0.572254,0.529412,0.550000,None,None,Default XGBoost parameters
6,XGBoost,SMOTEENN,0.732765,0.498305,0.786096,0.609959,None,None,XGBoost parameters with somte enn

In [48]:
# checks class distribution using counter
print("Before smtoe: ", Counter(y_train))

smote = SMOTE(random_state=42)

X_train_smote , y_train_smote = smote.fit_resample(X_train, y_train)

print("After smote: ", Counter(y_train_smote))


model_xgb_smote = XGBClassifier(random_state = 42)
model_xgb_smote.fit(X_train_smote, y_train_smote)

y_pred_xgb_smote = model_xgb_smote.predict(X_test)

print(classification_report(y_pred=y_pred_xgb_smote, y_true=y_test))

Before smtoe:  Counter({0: 4130, 1: 1495})
After smote:  Counter({0: 4130, 1: 4130})
              precision    recall  f1-score   support

           0       0.85      0.84      0.84      1033
           1       0.57      0.57      0.57       374

    accuracy                           0.77      1407
   macro avg       0.71      0.71      0.71      1407
weighted avg       0.77      0.77      0.77      1407

In [49]:
log_experiment(
    model_name="XGBoost",
    approach="smote",
    y_true=y_test,
    y_pred=y_pred_xgb_smote,
    notes="XGB post smote"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler
2,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max
3,DecisionTree,SMOTEENN,0.725657,0.489691,0.762032,0.596234,None,None,Decision Tree with smoteenn
4,RandomForest,SMOTEENN,0.718550,0.482026,0.788770,0.598377,None,None,Random Forest + SMOTEENN
5,XGBoost,Baseline,0.769723,0.572254,0.529412,0.550000,None,None,Default XGBoost parameters
6,XGBoost,SMOTEENN,0.732765,0.498305,0.786096,0.609959,None,None,XGBoost parameters with somte enn
7,XGBoost,smote,0.769723,0.565789,0.574866,0.570292,None,None,XGB post smote

In [50]:
# Check original distribution
print("Before ADASYN:", Counter(y_train))

# Apply ADASYN to training data only
adasyn = ADASYN(random_state=42)
X_train_adasyn, y_train_adasyn = adasyn.fit_resample(X_train, y_train)

# Check new distribution
print("After ADASYN:", Counter(y_train_adasyn))

# Train XGBoost on ADASYN-resampled data
model_xgb_adasyn = XGBClassifier(random_state=42)
model_xgb_adasyn.fit(X_train_adasyn, y_train_adasyn)

# Predict on the original test set
y_pred_xgb_adasyn = model_xgb_adasyn.predict(X_test)

# Evaluate
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred_xgb_adasyn))
print("\nClassification Report:\n", classification_report(y_test, y_pred_xgb_adasyn))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb_adasyn))

Before ADASYN: Counter({0: 4130, 1: 1495})
After ADASYN: Counter({0: 4130, 1: 4081})
Accuracy: 0.7633262260127932

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.83      0.84      1033
           1       0.55      0.57      0.56       374

    accuracy                           0.76      1407
   macro avg       0.70      0.70      0.70      1407
weighted avg       0.77      0.76      0.76      1407


Confusion Matrix:
 [[861 172]
 [161 213]]

In [51]:
log_experiment(
    model_name="XGBoost",
    approach="ADASYN",
    y_true=y_test,
    y_pred=y_pred_xgb_adasyn,
    notes="XGBoost parameters with ADASYN"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler
2,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max
3,DecisionTree,SMOTEENN,0.725657,0.489691,0.762032,0.596234,None,None,Decision Tree with smoteenn
4,RandomForest,SMOTEENN,0.718550,0.482026,0.788770,0.598377,None,None,Random Forest + SMOTEENN
5,XGBoost,Baseline,0.769723,0.572254,0.529412,0.550000,None,None,Default XGBoost parameters
6,XGBoost,SMOTEENN,0.732765,0.498305,0.786096,0.609959,None,None,XGBoost parameters with somte enn
7,XGBoost,smote,0.769723,0.565789,0.574866,0.570292,None,None,XGB post smote
8,XGBoost,ADASYN,0.763326,0.553247,0.569519,0.561265,None,None,XGBoost parameters with ADASYN

In [52]:
# Calculate scale_pos_weight (ratio of negative to positive class)
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
print(f"scale_pos_weight: {scale_pos_weight:.2f}")

# Train XGBoost with scale_pos_weight
model_xgb_weighted = XGBClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    eval_metric='logloss'  # avoids warnings
)

model_xgb_weighted.fit(X_train, y_train)
y_pred_weighted = model_xgb_weighted.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred_weighted))
print("\nClassification Report:\n", classification_report(y_test, y_pred_weighted))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_weighted))

scale_pos_weight: 2.76
Accuracy: 0.7476901208244492

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.77      0.82      1033
           1       0.52      0.69      0.59       374

    accuracy                           0.75      1407
   macro avg       0.70      0.73      0.70      1407
weighted avg       0.78      0.75      0.76      1407


Confusion Matrix:
 [[794 239]
 [116 258]]

In [53]:
log_experiment(
    model_name="XGBoost",
    approach="scale_pos_weight",
    y_true=y_test,
    y_pred=y_pred_weighted,
    notes="XGBoost parameters with scale pos weight"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler
2,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max
3,DecisionTree,SMOTEENN,0.725657,0.489691,0.762032,0.596234,None,None,Decision Tree with smoteenn
4,RandomForest,SMOTEENN,0.718550,0.482026,0.788770,0.598377,None,None,Random Forest + SMOTEENN
5,XGBoost,Baseline,0.769723,0.572254,0.529412,0.550000,None,None,Default XGBoost parameters
6,XGBoost,SMOTEENN,0.732765,0.498305,0.786096,0.609959,None,None,XGBoost parameters with somte enn
7,XGBoost,smote,0.769723,0.565789,0.574866,0.570292,None,None,XGB post smote
8,XGBoost,ADASYN,0.763326,0.553247,0.569519,0.561265,None,None,XGBoost parameters with ADASYN
9,XGBoost,scale_pos_weight,0.747690,0.519115,0.689840,0.592423,None,None,XGBoost parameters with scale pos weight

In [54]:
# Calculate the weight for the positive (minority) class
# Common approach: weight_positive = negative_count / positive_count
negative_count = (y_train == 0).sum()
positive_count = (y_train == 1).sum()
weight_positive = negative_count / positive_count if positive_count > 0 else 1
print(f"Negative class count: {negative_count}")
print(f"Positive class count: {positive_count}")
print(f"Weight for positive class: {weight_positive:.2f}")

# Create sample weights: higher weight for minority class
sample_weight = np.where(y_train == 1, weight_positive, 1.0)

# Train AdaBoost with sample weights
model_ada_weighted = AdaBoostClassifier(
    n_estimators=50,  # default, you can tune
    random_state=42
)

model_ada_weighted.fit(X_train, y_train, sample_weight=sample_weight)

# Predict and evaluate
y_pred_ada_weighted = model_ada_weighted.predict(X_test)

print("AdaBoost with sample weighting - Accuracy:", accuracy_score(y_test, y_pred_ada_weighted))
print("\nClassification Report:\n", classification_report(y_test, y_pred_ada_weighted))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_ada_weighted))

Negative class count: 4130
Positive class count: 1495
Weight for positive class: 2.76
AdaBoost with sample weighting - Accuracy: 0.7320540156361052

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.70      0.79      1033
           1       0.50      0.81      0.62       374

    accuracy                           0.73      1407
   macro avg       0.70      0.76      0.71      1407
weighted avg       0.80      0.73      0.75      1407


Confusion Matrix:
 [[726 307]
 [ 70 304]]

In [55]:
log_experiment(
    model_name="AdaBoost",
    approach="Sample Weighting",
    y_true=y_test,
    y_pred=y_pred_ada_weighted,
    notes="Default AdaBoost parameters"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler
2,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max
3,DecisionTree,SMOTEENN,0.725657,0.489691,0.762032,0.596234,None,None,Decision Tree with smoteenn
4,RandomForest,SMOTEENN,0.718550,0.482026,0.788770,0.598377,None,None,Random Forest + SMOTEENN
5,XGBoost,Baseline,0.769723,0.572254,0.529412,0.550000,None,None,Default XGBoost parameters
6,XGBoost,SMOTEENN,0.732765,0.498305,0.786096,0.609959,None,None,XGBoost parameters with somte enn
7,XGBoost,smote,0.769723,0.565789,0.574866,0.570292,None,None,XGB post smote
8,XGBoost,ADASYN,0.763326,0.553247,0.569519,0.561265,None,None,XGBoost parameters with ADASYN
9,XGBoost,scale_pos_weight,0.747690,0.519115,0.689840,0.592423,None,None,XGBoost parameters with scale pos weight
10,AdaBoost,Sample Weighting,0.732054,0.497545,0.812834,0.617259,None,None,Default AdaBoost parameters

In [77]:
# Save the best model to a .pkl file
joblib.dump(model_ada_weighted, 'best_ada_boost_churn_model.pkl')

print("Best model successfully saved as 'best_optuna_churn_model.pkl'")

Best model successfully saved as 'best_optuna_churn_model.pkl'

In [56]:
param_grid = {
    'max_depth': [3, 4, 5, 6, 7],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'n_estimators': [100, 200, 300, 400],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.2],
    'scale_pos_weight': [1, scale_pos_weight]  # try both balanced and weighted
}

xgb = XGBClassifier(random_state=42, eval_metric='logloss')

# Use 'f1' or 'recall' scoring since churn is imbalanced
search = RandomizedSearchCV(
    xgb,
    param_grid,
    n_iter=50,
    cv=5,
    scoring='f1',  # or 'recall' if catching churn is priority
    random_state=42,
    n_jobs=-1
)

search.fit(X_train, y_train)

print("Best parameters:", search.best_params_)
print("Best CV F1 score:", search.best_score_)

# Use best model
best_model = search.best_estimator_
y_pred_best = best_model.predict(X_test)
print("\nTest Classification Report:\n", classification_report(y_test, y_pred_best))

Best parameters: {'subsample': 0.8, 'scale_pos_weight': np.float64(2.762541806020067), 'n_estimators': 400, 'min_child_weight': 5, 'max_depth': 4, 'learning_rate': 0.01, 'gamma': 0, 'colsample_bytree': 0.7}
Best CV F1 score: 0.6331700864298416

Test Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.70      0.79      1033
           1       0.49      0.82      0.61       374

    accuracy                           0.73      1407
   macro avg       0.70      0.76      0.70      1407
weighted avg       0.80      0.73      0.74      1407

In [57]:
log_experiment(
    model_name="XGBoost",
    approach="RandomizedSearchCV",
    y_true=y_test,
    y_pred=y_pred_best,
    notes="XGBoost parameters with randomized search cv"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler
2,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max
3,DecisionTree,SMOTEENN,0.725657,0.489691,0.762032,0.596234,None,None,Decision Tree with smoteenn
4,RandomForest,SMOTEENN,0.718550,0.482026,0.788770,0.598377,None,None,Random Forest + SMOTEENN
5,XGBoost,Baseline,0.769723,0.572254,0.529412,0.550000,None,None,Default XGBoost parameters
6,XGBoost,SMOTEENN,0.732765,0.498305,0.786096,0.609959,None,None,XGBoost parameters with somte enn
7,XGBoost,smote,0.769723,0.565789,0.574866,0.570292,None,None,XGB post smote
8,XGBoost,ADASYN,0.763326,0.553247,0.569519,0.561265,None,None,XGBoost parameters with ADASYN
9,XGBoost,scale_pos_weight,0.747690,0.519115,0.689840,0.592423,None,None,XGBoost parameters with scale pos weight
10,AdaBoost,Sample Weighting,0.732054,0.497545,0.812834,0.617259,None,None,Default AdaBoost parameters
11,XGBoost,RandomizedSearchCV,0.728500,0.493528,0.815508,0.614919,None,None,XGBoost parameters with randomized search cv

In [58]:
# Save this model

import joblib

# Save the best model to a .pkl file
joblib.dump(best_model, 'best_xgboost_churn_model.pkl')

print("Best model successfully saved as 'best_xgboost_churn_model.pkl'")

Best model successfully saved as 'best_xgboost_churn_model.pkl'

In [59]:
model_rf = RandomForestClassifier(
    class_weight='balanced',
    random_state=42,
    n_estimators=300,
    max_depth=6
)
model_rf.fit(X_train, y_train)
y_pred_rf = model_rf.predict(X_test)
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.90      0.69      0.78      1033
           1       0.48      0.80      0.60       374

    accuracy                           0.72      1407
   macro avg       0.69      0.74      0.69      1407
weighted avg       0.79      0.72      0.73      1407

In [60]:
log_experiment(
    model_name="RandomForest",
    approach="Class Weight",
    y_true=y_test,
    y_pred=y_pred_rf,
    notes="Default Random Forest parameters"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler
2,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max
3,DecisionTree,SMOTEENN,0.725657,0.489691,0.762032,0.596234,None,None,Decision Tree with smoteenn
4,RandomForest,SMOTEENN,0.718550,0.482026,0.788770,0.598377,None,None,Random Forest + SMOTEENN
5,XGBoost,Baseline,0.769723,0.572254,0.529412,0.550000,None,None,Default XGBoost parameters
6,XGBoost,SMOTEENN,0.732765,0.498305,0.786096,0.609959,None,None,XGBoost parameters with somte enn
7,XGBoost,smote,0.769723,0.565789,0.574866,0.570292,None,None,XGB post smote
8,XGBoost,ADASYN,0.763326,0.553247,0.569519,0.561265,None,None,XGBoost parameters with ADASYN
9,XGBoost,scale_pos_weight,0.747690,0.519115,0.689840,0.592423,None,None,XGBoost parameters with scale pos weight
10,AdaBoost,Sample Weighting,0.732054,0.497545,0.812834,0.617259,None,None,Default AdaBoost parameters
11,XGBoost,RandomizedSearchCV,0.728500,0.493528,0.815508,0.614919,None,None,XGBoost parameters with randomized search cv
12,RandomForest,Class Weight,0.718550,0.482258,0.799465,0.601610,None,None,Default Random Forest parameters

In [61]:
from catboost import CatBoostClassifier

model_cat = CatBoostClassifier(
    auto_class_weights='Balanced',  # or 'SqrtBalanced'
    verbose=0,
    random_state=42
)
model_cat.fit(X_train, y_train)
y_pred_cat = model_cat.predict(X_test)
print(classification_report(y_test, y_pred_cat))

              precision    recall  f1-score   support

           0       0.90      0.73      0.81      1033
           1       0.51      0.77      0.61       374

    accuracy                           0.74      1407
   macro avg       0.70      0.75      0.71      1407
weighted avg       0.79      0.74      0.76      1407

In [62]:
log_experiment(
    model_name="CatBoost",
    approach="Class Weight",
    y_true=y_test,
    y_pred=y_pred_cat,
    notes="Default CatBoost parameters"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler
2,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max
3,DecisionTree,SMOTEENN,0.725657,0.489691,0.762032,0.596234,None,None,Decision Tree with smoteenn
4,RandomForest,SMOTEENN,0.718550,0.482026,0.788770,0.598377,None,None,Random Forest + SMOTEENN
5,XGBoost,Baseline,0.769723,0.572254,0.529412,0.550000,None,None,Default XGBoost parameters
6,XGBoost,SMOTEENN,0.732765,0.498305,0.786096,0.609959,None,None,XGBoost parameters with somte enn
7,XGBoost,smote,0.769723,0.565789,0.574866,0.570292,None,None,XGB post smote
8,XGBoost,ADASYN,0.763326,0.553247,0.569519,0.561265,None,None,XGBoost parameters with ADASYN
9,XGBoost,scale_pos_weight,0.747690,0.519115,0.689840,0.592423,None,None,XGBoost parameters with scale pos weight
10,AdaBoost,Sample Weighting,0.732054,0.497545,0.812834,0.617259,None,None,Default AdaBoost parameters
11,XGBoost,RandomizedSearchCV,0.728500,0.493528,0.815508,0.614919,None,None,XGBoost parameters with randomized search cv
12,RandomForest,Class Weight,0.718550,0.482258,0.799465,0.601610,None,None,Default Random Forest parameters
13,CatBoost,Class Weight,0.743426,0.511586,0.767380,0.613904,None,None,Default CatBoost parameters

In [63]:
from lightgbm import LGBMClassifier

model_lgb = LGBMClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42
)
model_lgb.fit(X_train, y_train)
y_pred_lgb = model_lgb.predict(X_test)
print(classification_report(y_test, y_pred_lgb))

[LightGBM] [Info] Number of positive: 1495, number of negative: 4130
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000826 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 606
[LightGBM] [Info] Number of data points in the train set: 5625, number of used features: 34
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.265778 -> initscore=-1.016151
[LightGBM] [Info] Start training from score -1.016151
              precision    recall  f1-score   support

           0       0.89      0.75      0.81      1033
           1       0.52      0.75      0.61       374

    accuracy                           0.75      1407
   macro avg       0.71      0.75      0.71      1407
weighted avg       0.79      0.75      0.76      1407

In [64]:
log_experiment(
    model_name="LightGBM",
    approach="scale_pos_weight",
    y_true=y_test,
    y_pred=y_pred_lgb,
    notes="Default LightGBM parameters"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler
2,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max
3,DecisionTree,SMOTEENN,0.725657,0.489691,0.762032,0.596234,None,None,Decision Tree with smoteenn
4,RandomForest,SMOTEENN,0.718550,0.482026,0.788770,0.598377,None,None,Random Forest + SMOTEENN
5,XGBoost,Baseline,0.769723,0.572254,0.529412,0.550000,None,None,Default XGBoost parameters
6,XGBoost,SMOTEENN,0.732765,0.498305,0.786096,0.609959,None,None,XGBoost parameters with somte enn
7,XGBoost,smote,0.769723,0.565789,0.574866,0.570292,None,None,XGB post smote
8,XGBoost,ADASYN,0.763326,0.553247,0.569519,0.561265,None,None,XGBoost parameters with ADASYN
9,XGBoost,scale_pos_weight,0.747690,0.519115,0.689840,0.592423,None,None,XGBoost parameters with scale pos weight
10,AdaBoost,Sample Weighting,0.732054,0.497545,0.812834,0.617259,None,None,Default AdaBoost parameters
11,XGBoost,RandomizedSearchCV,0.728500,0.493528,0.815508,0.614919,None,None,XGBoost parameters with randomized search cv
12,RandomForest,Class Weight,0.718550,0.482258,0.799465,0.601610,None,None,Default Random Forest parameters
13,CatBoost,Class Weight,0.743426,0.511586,0.767380,0.613904,None,None,Default CatBoost parameters
14,LightGBM,scale_pos_weight,0.749112,0.519409,0.751337,0.614208,None,None,Default LightGBM parameters

In [65]:
def objective(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 1),  # L1 regularization
        'reg_lambda': trial.suggest_float('reg_lambda', 0, 2), # L2 regularization
        'scale_pos_weight': trial.suggest_categorical('scale_pos_weight', [1, scale_pos_weight]),
        'random_state': 42,
        'eval_metric': 'logloss'
    }

    model = XGBClassifier(**params)

    # Use F1 for minority class as scorer
    f1_scorer = make_scorer(f1_score, average='binary', pos_label=1)
    score = cross_val_score(model, X_train, y_train, cv=5, scoring=f1_scorer, n_jobs=-1).mean()

    return score

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)  # Increase trials for better results

print("Best parameters:", study.best_params)
print("Best CV F1 score:", study.best_value)

# Train final model with best params
best_model_optuna = XGBClassifier(**study.best_params)
best_model_optuna.fit(X_train, y_train)
y_pred_optuna = best_model_optuna.predict(X_test)
print(classification_report(y_test, y_pred_optuna))

[I 2026-09-28 13:42:21,651] A new study created in memory with name: no-name-159efdef-540d-4b9b-9f85-152fa344a4ad
[I 2026-09-28 13:42:24,066] Trial 0 finished with value: 0.5537041471903276 and parameters: {'max_depth': 9, 'learning_rate': 0.06599856987178462, 'n_estimators': 617, 'subsample': 0.8430644234009799, 'colsample_bytree': 0.639474130555922, 'min_child_weight': 6, 'gamma': 0.19509710286148502, 'reg_alpha': 0.6040254086911775, 'reg_lambda': 0.9289772813498343, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.5537041471903276.
[I 2026-09-28 13:42:26,859] Trial 1 finished with value: 0.5853599050670807 and parameters: {'max_depth': 8, 'learning_rate': 0.2229663573229539, 'n_estimators': 999, 'subsample': 0.8967547065674091, 'colsample_bytree': 0.9378492229367507, 'min_child_weight': 2, 'gamma': 0.4982377010418283, 'reg_alpha': 0.7265601602232872, 'reg_lambda': 1.9727100565169533, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 1 with value: 0.5853599050670807.
[I 2026-09-28 13:42:29,575] Trial 2 finished with value: 0.5970626451871215 and parameters: {'max_depth': 3, 'learning_rate': 0.12512279663268375, 'n_estimators': 989, 'subsample': 0.7087776428991756, 'colsample_bytree': 0.9484776916641385, 'min_child_weight': 2, 'gamma': 0.4550026112653456, 'reg_alpha': 0.31787657250932366, 'reg_lambda': 0.7641481184481094, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.5970626451871215.
[I 2026-09-28 13:42:30,685] Trial 3 finished with value: 0.6337022972402415 and parameters: {'max_depth': 4, 'learning_rate': 0.01277730965118443, 'n_estimators': 330, 'subsample': 0.808836118567714, 'colsample_bytree': 0.9869604388567752, 'min_child_weight': 7, 'gamma': 0.14801017744187678, 'reg_alpha': 0.22583853222174466, 'reg_lambda': 0.8748053451906086, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 3 with value: 0.6337022972402415.
[I 2026-09-28 13:42:33,481] Trial 4 finished with value: 0.6205988689352644 and parameters: {'max_depth': 5, 'learning_rate': 0.03043704858696959, 'n_estimators': 895, 'subsample': 0.760759022618785, 'colsample_bytree': 0.6634059660324431, 'min_child_weight': 6, 'gamma': 0.3737256350312965, 'reg_alpha': 0.06940653213449655, 'reg_lambda': 0.4392262008330581, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 3 with value: 0.6337022972402415.
[I 2026-09-28 13:42:37,069] Trial 5 finished with value: 0.5758541338143001 and parameters: {'max_depth': 9, 'learning_rate': 0.0564120239665726, 'n_estimators': 817, 'subsample': 0.7078388987742542, 'colsample_bytree': 0.764477128052557, 'min_child_weight': 1, 'gamma': 0.1358404770891935, 'reg_alpha': 0.8558492069533796, 'reg_lambda': 0.1874097122023477, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 3 with value: 0.6337022972402415.
[I 2026-09-28 13:42:37,726] Trial 6 finished with value: 0.5572531037003181 and parameters: {'max_depth': 7, 'learning_rate': 0.18802106271602528, 'n_estimators': 132, 'subsample': 0.8452044033356341, 'colsample_bytree': 0.7704320369792923, 'min_child_weight': 4, 'gamma': 0.0013473331156941826, 'reg_alpha': 0.7745798570355164, 'reg_lambda': 1.5119618199091502, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.6337022972402415.
[I 2026-09-28 13:42:39,982] Trial 7 finished with value: 0.5719419562598445 and parameters: {'max_depth': 5, 'learning_rate': 0.03788072384999613, 'n_estimators': 738, 'subsample': 0.9725965242519992, 'colsample_bytree': 0.9451035073857699, 'min_child_weight': 10, 'gamma': 0.17168913298078714, 'reg_alpha': 0.7586038734020017, 'reg_lambda': 0.5925209946935381, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.6337022972402415.
[I 2026-09-28 13:42:42,875] Trial 8 finished with value: 0.6005750181706712 and parameters: {'max_depth': 3, 'learning_rate': 0.18110578117996146, 'n_estimators': 877, 'subsample': 0.9488151449729276, 'colsample_bytree': 0.722393717109301, 'min_child_weight': 8, 'gamma': 0.16448781569522464, 'reg_alpha': 0.6077231508390938, 'reg_lambda': 0.894144189400419, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 3 with value: 0.6337022972402415.
[I 2026-09-28 13:42:45,833] Trial 9 finished with value: 0.5333801421140008 and parameters: {'max_depth': 6, 'learning_rate': 0.20224296076140127, 'n_estimators': 795, 'subsample': 0.7827392506899371, 'colsample_bytree': 0.7089164234863452, 'min_child_weight': 2, 'gamma': 0.060772291428832004, 'reg_alpha': 0.504283827361391, 'reg_lambda': 1.1801938533329612, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.6337022972402415.
[I 2026-09-28 13:42:47,233] Trial 10 finished with value: 0.6218035893749608 and parameters: {'max_depth': 5, 'learning_rate': 0.04951077944595756, 'n_estimators': 391, 'subsample': 0.7303136894952709, 'colsample_bytree': 0.9843295082709542, 'min_child_weight': 6, 'gamma': 0.1163577754907186, 'reg_alpha': 0.15258860162962284, 'reg_lambda': 1.0353858808703458, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 3 with value: 0.6337022972402415.
[I 2026-09-28 13:42:48,720] Trial 11 finished with value: 0.6351475484336001 and parameters: {'max_depth': 3, 'learning_rate': 0.013366615961707944, 'n_estimators': 456, 'subsample': 0.6882872817908325, 'colsample_bytree': 0.9542519957610223, 'min_child_weight': 6, 'gamma': 0.18473583218509249, 'reg_alpha': 0.3820127597514478, 'reg_lambda': 1.1841171631736753, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 11 with value: 0.6351475484336001.
[I 2026-09-28 13:42:49,507] Trial 12 finished with value: 0.6304820200661164 and parameters: {'max_depth': 4, 'learning_rate': 0.011995620874750064, 'n_estimators': 199, 'subsample': 0.666050594822961, 'colsample_bytree': 0.9262541657735733, 'min_child_weight': 5, 'gamma': 0.2665283435944202, 'reg_alpha': 0.36226828099273745, 'reg_lambda': 1.4135547940877962, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 11 with value: 0.6351475484336001.
[I 2026-09-28 13:42:50,697] Trial 13 finished with value: 0.6341428982091667 and parameters: {'max_depth': 4, 'learning_rate': 0.011723665142713155, 'n_estimators': 355, 'subsample': 0.8502626907984439, 'colsample_bytree': 0.9684509161373941, 'min_child_weight': 8, 'gamma': 0.0647563484324905, 'reg_alpha': 0.212893613518787, 'reg_lambda': 0.8861805111054613, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 11 with value: 0.6351475484336001.
[I 2026-09-28 13:42:51,944] Trial 14 finished with value: 0.6343405379542348 and parameters: {'max_depth': 5, 'learning_rate': 0.021828882561335784, 'n_estimators': 322, 'subsample': 0.6479780892202411, 'colsample_bytree': 0.9561728779903939, 'min_child_weight': 8, 'gamma': 0.19375024891898004, 'reg_alpha': 0.6752373833213303, 'reg_lambda': 0.9594303200082157, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 11 with value: 0.6351475484336001.
[I 2026-09-28 13:42:53,438] Trial 15 finished with value: 0.6276191407489529 and parameters: {'max_depth': 6, 'learning_rate': 0.0276469713008768, 'n_estimators': 337, 'subsample': 0.6205556690213874, 'colsample_bytree': 0.9489795467098562, 'min_child_weight': 8, 'gamma': 0.16673142824833584, 'reg_alpha': 0.9455408986160614, 'reg_lambda': 0.9512060033400762, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 11 with value: 0.6351475484336001.
[I 2026-09-28 13:42:54,929] Trial 16 finished with value: 0.6308394697312864 and parameters: {'max_depth': 3, 'learning_rate': 0.034092584118161184, 'n_estimators': 504, 'subsample': 0.6028733245576476, 'colsample_bytree': 0.9905117136210025, 'min_child_weight': 6, 'gamma': 0.17705805723123763, 'reg_alpha': 0.3735170657573113, 'reg_lambda': 0.6841900258665148, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 11 with value: 0.6351475484336001.
[I 2026-09-28 13:42:56,042] Trial 17 finished with value: 0.6317792665289234 and parameters: {'max_depth': 3, 'learning_rate': 0.012532719615248879, 'n_estimators': 343, 'subsample': 0.611864468780683, 'colsample_bytree': 0.7920291956004324, 'min_child_weight': 9, 'gamma': 0.1680512142985031, 'reg_alpha': 0.6018059973759065, 'reg_lambda': 0.9738870355969008, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 11 with value: 0.6351475484336001.
[I 2026-09-28 13:42:56,950] Trial 18 finished with value: 0.6334859668632211 and parameters: {'max_depth': 7, 'learning_rate': 0.024606203307829127, 'n_estimators': 194, 'subsample': 0.6181991224870782, 'colsample_bytree': 0.8715719399076728, 'min_child_weight': 7, 'gamma': 0.20905979952456225, 'reg_alpha': 0.7166354658024224, 'reg_lambda': 0.7339101601641358, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 11 with value: 0.6351475484336001.
[I 2026-09-28 13:42:59,075] Trial 19 finished with value: 0.6278058076653946 and parameters: {'max_depth': 4, 'learning_rate': 0.023190274913545025, 'n_estimators': 673, 'subsample': 0.620203860163088, 'colsample_bytree': 0.9209331267329984, 'min_child_weight': 7, 'gamma': 0.09026240989085382, 'reg_alpha': 0.4591128321565894, 'reg_lambda': 0.8827677931516438, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 11 with value: 0.6351475484336001.
[I 2026-09-28 13:42:59,836] Trial 20 finished with value: 0.6324388141804225 and parameters: {'max_depth': 4, 'learning_rate': 0.017481162014868355, 'n_estimators': 195, 'subsample': 0.7107651364308722, 'colsample_bytree': 0.828765516480747, 'min_child_weight': 7, 'gamma': 0.07964753247259657, 'reg_alpha': 0.4745578481751136, 'reg_lambda': 0.964403657190938, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 11 with value: 0.6351475484336001.
[I 2026-09-28 13:43:01,027] Trial 21 finished with value: 0.6283036362640166 and parameters: {'max_depth': 5, 'learning_rate': 0.027225603000267926, 'n_estimators': 300, 'subsample': 0.6613155865732214, 'colsample_bytree': 0.9649784026123225, 'min_child_weight': 8, 'gamma': 0.26822408205904885, 'reg_alpha': 0.3568107515836894, 'reg_lambda': 0.7810827138162374, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 11 with value: 0.6351475484336001.
[I 2026-09-28 13:43:02,573] Trial 22 finished with value: 0.6366235524887568 and parameters: {'max_depth': 3, 'learning_rate': 0.014359388185552373, 'n_estimators': 428, 'subsample': 0.7163902586142495, 'colsample_bytree': 0.9623132633324863, 'min_child_weight': 5, 'gamma': 0.19451921024075824, 'reg_alpha': 0.048345441089093, 'reg_lambda': 1.276981141787838, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 22 with value: 0.6366235524887568.
[I 2026-09-28 13:43:04,492] Trial 23 finished with value: 0.6344053126399232 and parameters: {'max_depth': 4, 'learning_rate': 0.013359699667092929, 'n_estimators': 542, 'subsample': 0.7448246864706061, 'colsample_bytree': 0.96389233133135, 'min_child_weight': 7, 'gamma': 0.2129573099302568, 'reg_alpha': 0.12709826081180353, 'reg_lambda': 1.011558659992908, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 22 with value: 0.6366235524887568.
[I 2026-09-28 13:43:06,107] Trial 24 finished with value: 0.6362106940946017 and parameters: {'max_depth': 3, 'learning_rate': 0.019899012899513475, 'n_estimators': 469, 'subsample': 0.7048466377083205, 'colsample_bytree': 0.9699931842191974, 'min_child_weight': 3, 'gamma': 0.18058991512103123, 'reg_alpha': 0.10299503859552145, 'reg_lambda': 0.9251992460115155, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 22 with value: 0.6366235524887568.
[I 2026-09-28 13:43:07,904] Trial 25 finished with value: 0.6286622557820353 and parameters: {'max_depth': 5, 'learning_rate': 0.01813128791372444, 'n_estimators': 449, 'subsample': 0.719473318512831, 'colsample_bytree': 0.990126782507235, 'min_child_weight': 4, 'gamma': 0.23247964809968305, 'reg_alpha': 0.01136778563336907, 'reg_lambda': 0.8800862908613409, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 22 with value: 0.6366235524887568.
[I 2026-09-28 13:43:09,118] Trial 26 finished with value: 0.6385445049347643 and parameters: {'max_depth': 4, 'learning_rate': 0.018422797370387378, 'n_estimators': 310, 'subsample': 0.7504765273368896, 'colsample_bytree': 0.866525026142444, 'min_child_weight': 4, 'gamma': 0.17454609109613273, 'reg_alpha': 0.1718129622009591, 'reg_lambda': 1.0561041231147128, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.
[I 2026-09-28 13:43:10,326] Trial 27 finished with value: 0.6348462068740358 and parameters: {'max_depth': 3, 'learning_rate': 0.01595404098481019, 'n_estimators': 379, 'subsample': 0.6060022089204906, 'colsample_bytree': 0.8814125585260292, 'min_child_weight': 3, 'gamma': 0.11574837065847915, 'reg_alpha': 0.026487666116979725, 'reg_lambda': 1.255849710663992, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.
[I 2026-09-28 13:43:12,169] Trial 28 finished with value: 0.6328066342934237 and parameters: {'max_depth': 3, 'learning_rate': 0.02392477522766496, 'n_estimators': 620, 'subsample': 0.643960140778409, 'colsample_bytree': 0.8087321750029133, 'min_child_weight': 4, 'gamma': 0.2131505143420641, 'reg_alpha': 0.03326265084142026, 'reg_lambda': 1.2083392613650914, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.
[I 2026-09-28 13:43:13,858] Trial 29 finished with value: 0.6345763496319474 and parameters: {'max_depth': 5, 'learning_rate': 0.023445030748114572, 'n_estimators': 420, 'subsample': 0.7374019624345162, 'colsample_bytree': 0.9447311549956724, 'min_child_weight': 4, 'gamma': 0.27190703696786644, 'reg_alpha': 0.24008915295653205, 'reg_lambda': 1.0023078379207921, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.
[I 2026-09-28 13:43:15,617] Trial 30 finished with value: 0.6331605084564224 and parameters: {'max_depth': 3, 'learning_rate': 0.024611150722282538, 'n_estimators': 619, 'subsample': 0.7361959770282571, 'colsample_bytree': 0.9147740887446979, 'min_child_weight': 5, 'gamma': 0.13269680156069802, 'reg_alpha': 0.17465831682184427, 'reg_lambda': 1.1951955598306234, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.
[I 2026-09-28 13:43:16,390] Trial 31 finished with value: 0.6345747147627583 and parameters: {'max_depth': 3, 'learning_rate': 0.017298949154031355, 'n_estimators': 210, 'subsample': 0.6650565084935457, 'colsample_bytree': 0.9521530557683194, 'min_child_weight': 5, 'gamma': 0.13713734371421069, 'reg_alpha': 0.08661867253113648, 'reg_lambda': 0.9728711558764003, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.
[I 2026-09-28 13:43:17,582] Trial 32 finished with value: 0.6333657199347067 and parameters: {'max_depth': 3, 'learning_rate': 0.011128289486401705, 'n_estimators': 389, 'subsample': 0.6965135122633855, 'colsample_bytree': 0.9372117288841879, 'min_child_weight': 7, 'gamma': 0.27922476517872075, 'reg_alpha': 0.16130416979660775, 'reg_lambda': 1.6555714282319012, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.
[I 2026-09-28 13:43:18,898] Trial 33 finished with value: 0.6315909263978855 and parameters: {'max_depth': 5, 'learning_rate': 0.01801503712602791, 'n_estimators': 348, 'subsample': 0.6805845587383526, 'colsample_bytree': 0.9590994145448577, 'min_child_weight': 5, 'gamma': 0.19957176306658345, 'reg_alpha': 0.06577145460113454, 'reg_lambda': 1.3141269402820108, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.
[I 2026-09-28 13:43:20,135] Trial 34 finished with value: 0.6385089337450282 and parameters: {'max_depth': 4, 'learning_rate': 0.015545438766039515, 'n_estimators': 369, 'subsample': 0.7125695471820339, 'colsample_bytree': 0.9441056883670287, 'min_child_weight': 6, 'gamma': 0.26462963395955263, 'reg_alpha': 0.36281584422231866, 'reg_lambda': 1.330381380249744, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.
[I 2026-09-28 13:43:21,632] Trial 35 finished with value: 0.6326433698397314 and parameters: {'max_depth': 4, 'learning_rate': 0.019955142374671254, 'n_estimators': 432, 'subsample': 0.6735054272075962, 'colsample_bytree': 0.9979851874723451, 'min_child_weight': 1, 'gamma': 0.16798404736620204, 'reg_alpha': 0.1469819458547944, 'reg_lambda': 1.1190438234681355, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.
[I 2026-09-28 13:43:22,653] Trial 36 finished with value: 0.6333919777753153 and parameters: {'max_depth': 3, 'learning_rate': 0.02269370198386876, 'n_estimators': 324, 'subsample': 0.6875617744341513, 'colsample_bytree': 0.9568253684236864, 'min_child_weight': 2, 'gamma': 0.14934033188548904, 'reg_alpha': 0.1739832886919133, 'reg_lambda': 0.725799379429317, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.
[I 2026-09-28 13:43:24,051] Trial 37 finished with value: 0.6357864516403336 and parameters: {'max_depth': 3, 'learning_rate': 0.01993348603327042, 'n_estimators': 415, 'subsample': 0.7693192471527793, 'colsample_bytree': 0.9868577093770328, 'min_child_weight': 4, 'gamma': 0.17487204537199957, 'reg_alpha': 0.09468935549366345, 'reg_lambda': 1.2228660407708716, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.
[I 2026-09-28 13:43:25,031] Trial 38 finished with value: 0.6314391083517219 and parameters: {'max_depth': 4, 'learning_rate': 0.012147037658728538, 'n_estimators': 279, 'subsample': 0.7349945405543242, 'colsample_bytree': 0.8971940647157811, 'min_child_weight': 4, 'gamma': 0.18540972188269958, 'reg_alpha': 0.0009371823639366603, 'reg_lambda': 1.3002304800584181, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.
[I 2026-09-28 13:43:26,334] Trial 39 finished with value: 0.6315608004867574 and parameters: {'max_depth': 3, 'learning_rate': 0.010363649804730061, 'n_estimators': 387, 'subsample': 0.7443206956365993, 'colsample_bytree': 0.9617264878075665, 'min_child_weight': 5, 'gamma': 0.3155013003710101, 'reg_alpha': 0.22175548198854234, 'reg_lambda': 1.0315328641420582, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.
[I 2026-09-28 13:43:27,870] Trial 40 finished with value: 0.6317360772217491 and parameters: {'max_depth': 4, 'learning_rate': 0.020743269792444438, 'n_estimators': 489, 'subsample': 0.7603178637529839, 'colsample_bytree': 0.8994403542468963, 'min_child_weight': 4, 'gamma': 0.20945105175071638, 'reg_alpha': 0.04497034461921882, 'reg_lambda': 1.3221260739201957, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.
[I 2026-09-28 13:43:28,814] Trial 41 finished with value: 0.6310535014727879 and parameters: {'max_depth': 3, 'learning_rate': 0.01938889629148465, 'n_estimators': 281, 'subsample': 0.7800484745418993, 'colsample_bytree': 0.9577726305523361, 'min_child_weight': 2, 'gamma': 0.2341904624394568, 'reg_alpha': 0.04605187076860026, 'reg_lambda': 1.301145990385866, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.
[I 2026-09-28 13:43:29,635] Trial 42 finished with value: 0.633466015706059 and parameters: {'max_depth': 3, 'learning_rate': 0.015530624088567653, 'n_estimators': 227, 'subsample': 0.730124227252271, 'colsample_bytree': 0.9883538531874185, 'min_child_weight': 6, 'gamma': 0.2155804791715635, 'reg_alpha': 0.009220291639486483, 'reg_lambda': 1.030042312778319, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 26 with value: 0.6385445049347643.

Best parameters: {'max_depth': 3, 'learning_rate': 0.013277632179717964, 'n_estimators': 563, 'subsample': 0.7529755645106877, 'colsample_bytree': 0.9170866064868098, 'min_child_weight': 4, 'gamma': 0.18307137983777227, 'reg_alpha': 0.039949748009223705, 'reg_lambda': 1.1796586425064333, 'scale_pos_weight': np.float64(2.762541806020067)}
Best CV F1 score: 0.6391569786848607
              precision    recall  f1-score   support

           0       0.91      0.70      0.79      1033
           1       0.49      0.80      0.61       374

    accuracy                           0.72      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.80      0.72      0.74      1407

In [66]:
log_experiment(
    model_name="XGBoost",
    approach="Optuna",
    y_true=y_test,
    y_pred=y_pred_optuna,
    notes="XGBoost parameters with optuna"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler
2,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max
3,DecisionTree,SMOTEENN,0.725657,0.489691,0.762032,0.596234,None,None,Decision Tree with smoteenn
4,RandomForest,SMOTEENN,0.718550,0.482026,0.788770,0.598377,None,None,Random Forest + SMOTEENN
5,XGBoost,Baseline,0.769723,0.572254,0.529412,0.550000,None,None,Default XGBoost parameters
6,XGBoost,SMOTEENN,0.732765,0.498305,0.786096,0.609959,None,None,XGBoost parameters with somte enn
7,XGBoost,smote,0.769723,0.565789,0.574866,0.570292,None,None,XGB post smote
8,XGBoost,ADASYN,0.763326,0.553247,0.569519,0.561265,None,None,XGBoost parameters with ADASYN
9,XGBoost,scale_pos_weight,0.747690,0.519115,0.689840,0.592423,None,None,XGBoost parameters with scale pos weight
10,AdaBoost,Sample Weighting,0.732054,0.497545,0.812834,0.617259,None,None,Default AdaBoost parameters
11,XGBoost,RandomizedSearchCV,0.728500,0.493528,0.815508,0.614919,None,None,XGBoost parameters with randomized search cv
12,RandomForest,Class Weight,0.718550,0.482258,0.799465,0.601610,None,None,Default Random Forest parameters
13,CatBoost,Class Weight,0.743426,0.511586,0.767380,0.613904,None,None,Default CatBoost parameters
14,LightGBM,scale_pos_weight,0.749112,0.519409,0.751337,0.614208,None,None,Default LightGBM parameters
15,XGBoost,Optuna,0.724236,0.488636,0.804813,0.608081,None,None,XGBoost parameters with optuna

In [67]:
# Save the best model to a .pkl file
joblib.dump(best_model_optuna, 'best_optuna_churn_model.pkl')

print("Best model successfully saved as 'best_optuna_churn_model.pkl'")

Best model successfully saved as 'best_optuna_churn_model.pkl'

In [68]:
# Base estimator
ada_base = DecisionTreeClassifier(
    random_state=42
)

# Hyperparameter search space
ada_param_grid = {
    'n_estimators': [50, 100, 150, 200, 300, 400, 500],
    'learning_rate': [0.01, 0.03, 0.05, 0.1, 0.2, 0.5, 1.0],

    # Hyperparameters of the base Decision Tree
    'estimator__max_depth': [1, 2, 3, 4, 5],
    'estimator__min_samples_split': [2, 5, 10, 20],
    'estimator__min_samples_leaf': [1, 2, 5, 10]
}

# AdaBoost model
ada = AdaBoostClassifier(
    estimator=ada_base,
    random_state=42
)

# Randomized Search
ada_search = RandomizedSearchCV(
    estimator=ada,
    param_distributions=ada_param_grid,
    n_iter=50,
    cv=5,
    scoring='f1',
    random_state=42,
    n_jobs=-1
)

# Train
ada_search.fit(X_train, y_train)

# Results
print("Best parameters:")
print(ada_search.best_params_)

print("\nBest CV F1 score:")
print(ada_search.best_score_)

# Best model
best_ada_model = ada_search.best_estimator_

# Test prediction
y_pred_ada = best_ada_model.predict(X_test)

print("\nTest Classification Report:")
print(classification_report(y_test, y_pred_ada))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_ada))

Best parameters:
{'n_estimators': 400, 'learning_rate': 0.5, 'estimator__min_samples_split': 10, 'estimator__min_samples_leaf': 2, 'estimator__max_depth': 3}

Best CV F1 score:
0.5953251727589182

Test Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.87      0.86      1033
           1       0.61      0.57      0.59       374

    accuracy                           0.79      1407
   macro avg       0.73      0.72      0.72      1407
weighted avg       0.78      0.79      0.78      1407


Confusion Matrix:
[[895 138]
 [162 212]]

In [69]:
log_experiment(
    model_name="AdaBoost",
    approach="RandomizedSearchCV",
    y_true=y_test,
    y_pred=y_pred_ada,
    notes="AdaBoost parameters with Randomized Search CV"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler
2,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max
3,DecisionTree,SMOTEENN,0.725657,0.489691,0.762032,0.596234,None,None,Decision Tree with smoteenn
4,RandomForest,SMOTEENN,0.718550,0.482026,0.788770,0.598377,None,None,Random Forest + SMOTEENN
5,XGBoost,Baseline,0.769723,0.572254,0.529412,0.550000,None,None,Default XGBoost parameters
6,XGBoost,SMOTEENN,0.732765,0.498305,0.786096,0.609959,None,None,XGBoost parameters with somte enn
7,XGBoost,smote,0.769723,0.565789,0.574866,0.570292,None,None,XGB post smote
8,XGBoost,ADASYN,0.763326,0.553247,0.569519,0.561265,None,None,XGBoost parameters with ADASYN
9,XGBoost,scale_pos_weight,0.747690,0.519115,0.689840,0.592423,None,None,XGBoost parameters with scale pos weight
10,AdaBoost,Sample Weighting,0.732054,0.497545,0.812834,0.617259,None,None,Default AdaBoost parameters
11,XGBoost,RandomizedSearchCV,0.728500,0.493528,0.815508,0.614919,None,None,XGBoost parameters with randomized search cv
12,RandomForest,Class Weight,0.718550,0.482258,0.799465,0.601610,None,None,Default Random Forest parameters
13,CatBoost,Class Weight,0.743426,0.511586,0.767380,0.613904,None,None,Default CatBoost parameters
14,LightGBM,scale_pos_weight,0.749112,0.519409,0.751337,0.614208,None,None,Default LightGBM parameters
15,XGBoost,Optuna,0.724236,0.488636,0.804813,0.608081,None,None,XGBoost parameters with optuna
16,AdaBoost,RandomizedSearchCV,0.786780,0.605714,0.566845,0.585635,None,None,AdaBoost parameters with Randomized Search CV

In [70]:
def ada_objective(trial):

    # Tune the Decision Tree separately
    tree = DecisionTreeClassifier(
        max_depth=trial.suggest_int(
            'max_depth',
            1,
            5
        ),

        min_samples_split=trial.suggest_int(
            'min_samples_split',
            2,
            20
        ),

        min_samples_leaf=trial.suggest_int(
            'min_samples_leaf',
            1,
            10
        ),

        random_state=42
    )

    # Tune AdaBoost parameters
    model = AdaBoostClassifier(
        estimator=tree,

        n_estimators=trial.suggest_int(
            'n_estimators',
            50,
            500
        ),

        learning_rate=trial.suggest_float(
            'learning_rate',
            0.01,
            1.0,
            log=True
        ),

        random_state=42
    )

    score = cross_val_score(
        model,
        X_train,
        y_train,
        cv=5,
        scoring='f1',
        n_jobs=-1
    ).mean()

    return score


# Create Optuna study
ada_study = optuna.create_study(
    direction='maximize'
)

# Run optimization
ada_study.optimize(
    ada_objective,
    n_trials=100
)

print("Best parameters:")
print(ada_study.best_params)

print("\nBest CV F1 score:")
print(ada_study.best_value)

[I 2026-09-28 13:47:11,028] A new study created in memory with name: no-name-9128d5f1-0584-461a-8969-cbb6970e9c65
[I 2026-09-28 13:47:13,768] Trial 0 finished with value: 0.38695696593944656 and parameters: {'max_depth': 2, 'min_samples_split': 8, 'min_samples_leaf': 8, 'n_estimators': 208, 'learning_rate': 0.018102855139999166}. Best is trial 0 with value: 0.38695696593944656.
[I 2026-09-28 13:47:15,246] Trial 1 finished with value: 0.5700499064533501 and parameters: {'max_depth': 2, 'min_samples_split': 18, 'min_samples_leaf': 5, 'n_estimators': 107, 'learning_rate': 0.4357413720414119}. Best is trial 1 with value: 0.5700499064533501.
[I 2026-09-28 13:47:18,740] Trial 2 finished with value: 0.5860123532622011 and parameters: {'max_depth': 4, 'min_samples_split': 17, 'min_samples_leaf': 9, 'n_estimators': 175, 'learning_rate': 0.05447231644330217}. Best is trial 2 with value: 0.5860123532622011.
[I 2026-09-28 13:47:23,150] Trial 3 finished with value: 0.420547104614331 and parameters: {'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 1, 'n_estimators': 335, 'learning_rate': 0.011605437996763081}. Best is trial 2 with value: 0.5860123532622011.
[I 2026-09-28 13:47:31,144] Trial 4 finished with value: 0.5874969705779172 and parameters: {'max_depth': 4, 'min_samples_split': 18, 'min_samples_leaf': 7, 'n_estimators': 396, 'learning_rate': 0.2077327681264883}. Best is trial 4 with value: 0.5874969705779172.
[I 2026-09-28 13:47:32,876] Trial 5 finished with value: 0.5093267520816507 and parameters: {'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 4, 'n_estimators': 100, 'learning_rate': 0.01185123878556858}. Best is trial 4 with value: 0.5874969705779172.
[I 2026-09-28 13:47:37,604] Trial 6 finished with value: 0.5886664015884561 and parameters: {'max_depth': 4, 'min_samples_split': 19, 'min_samples_leaf': 2, 'n_estimators': 234, 'learning_rate': 0.2979217143461409}. Best is trial 6 with value: 0.5886664015884561.
[I 2026-09-28 13:47:38,838] Trial 7 finished with value: 0.49131701492344443 and parameters: {'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 6, 'n_estimators': 57, 'learning_rate': 0.019499728903362767}. Best is trial 6 with value: 0.5886664015884561.
[I 2026-09-28 13:47:40,856] Trial 8 finished with value: 0.5825657196171317 and parameters: {'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 10, 'n_estimators': 94, 'learning_rate': 0.8500898267941298}. Best is trial 6 with value: 0.5886664015884561.
[I 2026-09-28 13:47:47,722] Trial 9 finished with value: 0.5898208777176321 and parameters: {'max_depth': 4, 'min_samples_split': 16, 'min_samples_leaf': 7, 'n_estimators': 335, 'learning_rate': 0.05010731709115264}. Best is trial 9 with value: 0.5898208777176321.
[I 2026-09-28 13:47:58,390] Trial 10 finished with value: 0.5826106621058853 and parameters: {'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 9, 'n_estimators': 471, 'learning_rate': 0.1841223965694818}. Best is trial 9 with value: 0.5898208777176321.
[I 2026-09-28 13:48:02,419] Trial 11 finished with value: 0.583421744024686 and parameters: {'max_depth': 4, 'min_samples_split': 16, 'min_samples_leaf': 4, 'n_estimators': 206, 'learning_rate': 0.05090663550516021}. Best is trial 9 with value: 0.5898208777176321.
[I 2026-09-28 13:48:07,265] Trial 12 finished with value: 0.5938372343268966 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 2, 'n_estimators': 288, 'learning_rate': 0.6076682926358878}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:48:12,896] Trial 13 finished with value: 0.5755894326772962 and parameters: {'max_depth': 3, 'min_samples_split': 18, 'min_samples_leaf': 3, 'n_estimators': 349, 'learning_rate': 0.04188765678330818}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:48:19,149] Trial 14 finished with value: 0.5856862792477144 and parameters: {'max_depth': 5, 'min_samples_split': 13, 'min_samples_leaf': 6, 'n_estimators': 290, 'learning_rate': 0.018195721222008614}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:48:25,174] Trial 15 finished with value: 0.568752657324646 and parameters: {'max_depth': 3, 'min_samples_split': 13, 'min_samples_leaf': 7, 'n_estimators': 369, 'learning_rate': 0.01690891901147201}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:48:34,385] Trial 16 finished with value: 0.5884915471364689 and parameters: {'max_depth': 4, 'min_samples_split': 15, 'min_samples_leaf': 6, 'n_estimators': 464, 'learning_rate': 0.05608922013498939}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:48:39,823] Trial 17 finished with value: 0.5844531470635334 and parameters: {'max_depth': 4, 'min_samples_split': 14, 'min_samples_leaf': 4, 'n_estimators': 274, 'learning_rate': 0.5198548216508201}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:48:42,760] Trial 18 finished with value: 0.5823674067327008 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 6, 'n_estimators': 172, 'learning_rate': 0.09583477755086135}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:48:46,406] Trial 19 finished with value: 0.5846927889087079 and parameters: {'max_depth': 2, 'min_samples_split': 20, 'min_samples_leaf': 2, 'n_estimators': 276, 'learning_rate': 0.8260947020785635}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:48:54,963] Trial 20 finished with value: 0.5832545927730416 and parameters: {'max_depth': 4, 'min_samples_split': 19, 'min_samples_leaf': 10, 'n_estimators': 434, 'learning_rate': 0.020785825485804613}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:49:01,725] Trial 21 finished with value: 0.5811102135298001 and parameters: {'max_depth': 4, 'min_samples_split': 14, 'min_samples_leaf': 1, 'n_estimators': 335, 'learning_rate': 0.4287266760720881}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:49:08,411] Trial 22 finished with value: 0.5764711833233951 and parameters: {'max_depth': 4, 'min_samples_split': 18, 'min_samples_leaf': 1, 'n_estimators': 330, 'learning_rate': 0.6342741963790129}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:49:11,762] Trial 23 finished with value: 0.5829115622760064 and parameters: {'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 2, 'n_estimators': 165, 'learning_rate': 0.37962184718716674}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:49:16,198] Trial 24 finished with value: 0.587497311955213 and parameters: {'max_depth': 3, 'min_samples_split': 18, 'min_samples_leaf': 2, 'n_estimators': 269, 'learning_rate': 0.2194522989812476}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:49:19,225] Trial 25 finished with value: 0.5827032023083164 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 4, 'n_estimators': 183, 'learning_rate': 0.3997296158938294}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:49:25,488] Trial 26 finished with value: 0.5884778377023884 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 4, 'n_estimators': 379, 'learning_rate': 0.9990982630249808}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:49:30,085] Trial 27 finished with value: 0.5880720352262003 and parameters: {'max_depth': 4, 'min_samples_split': 19, 'min_samples_leaf': 4, 'n_estimators': 215, 'learning_rate': 0.14499027354323665}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:49:37,274] Trial 28 finished with value: 0.586843632517823 and parameters: {'max_depth': 5, 'min_samples_split': 19, 'min_samples_leaf': 1, 'n_estimators': 311, 'learning_rate': 0.1553412860073986}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:49:42,044] Trial 29 finished with value: 0.5682267720724673 and parameters: {'max_depth': 4, 'min_samples_split': 17, 'min_samples_leaf': 4, 'n_estimators': 240, 'learning_rate': 0.9129098053197939}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:49:45,746] Trial 30 finished with value: 0.5893576365830041 and parameters: {'max_depth': 3, 'min_samples_split': 16, 'min_samples_leaf': 5, 'n_estimators': 215, 'learning_rate': 0.4466551528534511}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:49:52,639] Trial 31 finished with value: 0.5894522448579692 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 1, 'n_estimators': 401, 'learning_rate': 0.5125072615399635}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:50:00,362] Trial 32 finished with value: 0.5910376348036033 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 1, 'n_estimators': 469, 'learning_rate': 0.5030959005149422}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:50:07,255] Trial 33 finished with value: 0.5885171496171566 and parameters: {'max_depth': 2, 'min_samples_split': 17, 'min_samples_leaf': 2, 'n_estimators': 484, 'learning_rate': 0.7363298787535161}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:50:13,983] Trial 34 finished with value: 0.5815638057485553 and parameters: {'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 6, 'n_estimators': 321, 'learning_rate': 0.5449981223619433}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:50:20,156] Trial 35 finished with value: 0.5914303622743764 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 1, 'n_estimators': 371, 'learning_rate': 0.2899501710338436}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:50:28,093] Trial 36 finished with value: 0.5872792498922644 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 3, 'n_estimators': 486, 'learning_rate': 0.4053967312076817}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:50:36,243] Trial 37 finished with value: 0.5898885283401942 and parameters: {'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 2, 'n_estimators': 412, 'learning_rate': 0.20097337140058075}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:50:44,088] Trial 38 finished with value: 0.5902929347045959 and parameters: {'max_depth': 4, 'min_samples_split': 19, 'min_samples_leaf': 2, 'n_estimators': 404, 'learning_rate': 0.21153062091862238}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:50:49,239] Trial 39 finished with value: 0.5816759868586755 and parameters: {'max_depth': 2, 'min_samples_split': 20, 'min_samples_leaf': 1, 'n_estimators': 405, 'learning_rate': 0.33938544511136276}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:50:54,509] Trial 40 finished with value: 0.5834873366959196 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 2, 'n_estimators': 315, 'learning_rate': 0.9292575239834283}. Best is trial 12 with value: 0.5938372343268966.
[I 2026-09-28 13:51:02,963] Trial 41 finished with value: 0.5939227972660891 and parameters: {'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 3, 'n_estimators': 439, 'learning_rate': 0.2072082857181605}. Best is trial 41 with value: 0.5939227972660891.
[I 2026-09-28 13:51:12,169] Trial 42 finished with value: 0.5859888100068752 and parameters: {'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 3, 'n_estimators': 456, 'learning_rate': 0.10989710138327312}. Best is trial 41 with value: 0.5939227972660891.
[I 2026-09-28 13:51:19,755] Trial 43 finished with value: 0.5859901888769151 and parameters: {'max_depth': 3, 'min_samples_split': 19, 'min_samples_leaf': 1, 'n_estimators': 459, 'learning_rate': 0.7446713692824806}. Best is trial 41 with value: 0.5939227972660891.
[I 2026-09-28 13:51:25,992] Trial 44 finished with value: 0.5995101681778351 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 3, 'n_estimators': 377, 'learning_rate': 0.5193108072742092}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:51:31,381] Trial 45 finished with value: 0.5848188759346681 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 3, 'n_estimators': 319, 'learning_rate': 0.5622075921589199}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:51:44,697] Trial 46 finished with value: 0.5858681381378952 and parameters: {'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 1, 'n_estimators': 467, 'learning_rate': 0.45896821500159857}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:51:53,424] Trial 47 finished with value: 0.5831617224857166 and parameters: {'max_depth': 3, 'min_samples_split': 18, 'min_samples_leaf': 2, 'n_estimators': 399, 'learning_rate': 0.7249210106022868}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:52:04,430] Trial 48 finished with value: 0.5900894250492918 and parameters: {'max_depth': 3, 'min_samples_split': 18, 'min_samples_leaf': 1, 'n_estimators': 459, 'learning_rate': 0.21006378934576825}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:52:14,427] Trial 49 finished with value: 0.5918573074894243 and parameters: {'max_depth': 3, 'min_samples_split': 19, 'min_samples_leaf': 2, 'n_estimators': 440, 'learning_rate': 0.331373817771862}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:52:25,540] Trial 50 finished with value: 0.5857549842630174 and parameters: {'max_depth': 4, 'min_samples_split': 18, 'min_samples_leaf': 1, 'n_estimators': 415, 'learning_rate': 0.32019865834616434}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:52:34,346] Trial 51 finished with value: 0.5953566546620292 and parameters: {'max_depth': 3, 'min_samples_split': 19, 'min_samples_leaf': 3, 'n_estimators': 415, 'learning_rate': 0.27345725375844837}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:52:41,889] Trial 52 finished with value: 0.5743822056933128 and parameters: {'max_depth': 2, 'min_samples_split': 20, 'min_samples_leaf': 2, 'n_estimators': 451, 'learning_rate': 0.538319670173215}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:52:52,759] Trial 53 finished with value: 0.5860715452655807 and parameters: {'max_depth': 4, 'min_samples_split': 18, 'min_samples_leaf': 3, 'n_estimators': 417, 'learning_rate': 0.3611495083923614}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:53:02,000] Trial 54 finished with value: 0.593039352302877 and parameters: {'max_depth': 3, 'min_samples_split': 19, 'min_samples_leaf': 4, 'n_estimators': 441, 'learning_rate': 0.5253210107494515}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:53:13,747] Trial 55 finished with value: 0.5858607900430849 and parameters: {'max_depth': 4, 'min_samples_split': 19, 'min_samples_leaf': 3, 'n_estimators': 472, 'learning_rate': 0.5312981263788461}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:53:22,468] Trial 56 finished with value: 0.5853731001796196 and parameters: {'max_depth': 3, 'min_samples_split': 19, 'min_samples_leaf': 3, 'n_estimators': 430, 'learning_rate': 0.3943692438902711}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:53:29,060] Trial 57 finished with value: 0.5762421693072178 and parameters: {'max_depth': 2, 'min_samples_split': 18, 'min_samples_leaf': 2, 'n_estimators': 400, 'learning_rate': 0.32998695988761095}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:53:38,054] Trial 58 finished with value: 0.5857818126336836 and parameters: {'max_depth': 3, 'min_samples_split': 19, 'min_samples_leaf': 3, 'n_estimators': 434, 'learning_rate': 0.7225901982572389}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:53:46,482] Trial 59 finished with value: 0.5920316758605136 and parameters: {'max_depth': 3, 'min_samples_split': 17, 'min_samples_leaf': 3, 'n_estimators': 408, 'learning_rate': 0.21241260819249558}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:53:54,609] Trial 60 finished with value: 0.5743930169246487 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 2, 'n_estimators': 394, 'learning_rate': 0.9733296767708045}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:54:01,640] Trial 61 finished with value: 0.5912429462564848 and parameters: {'max_depth': 3, 'min_samples_split': 18, 'min_samples_leaf': 2, 'n_estimators': 343, 'learning_rate': 0.8536816168387629}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:54:11,132] Trial 62 finished with value: 0.5942110434514245 and parameters: {'max_depth': 3, 'min_samples_split': 18, 'min_samples_leaf': 2, 'n_estimators': 462, 'learning_rate': 0.3443860164230329}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:54:19,514] Trial 63 finished with value: 0.5925096710802562 and parameters: {'max_depth': 3, 'min_samples_split': 16, 'min_samples_leaf': 4, 'n_estimators': 413, 'learning_rate': 0.23062656782648547}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:54:27,971] Trial 64 finished with value: 0.5952013217601689 and parameters: {'max_depth': 3, 'min_samples_split': 16, 'min_samples_leaf': 3, 'n_estimators': 414, 'learning_rate': 0.31957550046091493}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:54:35,468] Trial 65 finished with value: 0.5908548831224393 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 3, 'n_estimators': 367, 'learning_rate': 0.5247795896156497}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:54:44,822] Trial 66 finished with value: 0.5928615565102934 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 3, 'n_estimators': 454, 'learning_rate': 0.16924176060145207}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:54:52,669] Trial 67 finished with value: 0.5910344404044175 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 3, 'n_estimators': 370, 'learning_rate': 0.3341032826295151}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:55:01,447] Trial 68 finished with value: 0.589879764909691 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 3, 'n_estimators': 425, 'learning_rate': 0.24584921119802045}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:55:10,108] Trial 69 finished with value: 0.5900262272610842 and parameters: {'max_depth': 3, 'min_samples_split': 17, 'min_samples_leaf': 2, 'n_estimators': 400, 'learning_rate': 0.3399700131272434}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:55:18,847] Trial 70 finished with value: 0.590174014756919 and parameters: {'max_depth': 3, 'min_samples_split': 18, 'min_samples_leaf': 4, 'n_estimators': 437, 'learning_rate': 0.16133342873575246}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:55:30,102] Trial 71 finished with value: 0.5921163480605158 and parameters: {'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 4, 'n_estimators': 451, 'learning_rate': 0.2849206906871865}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:55:36,335] Trial 72 finished with value: 0.5919605421211083 and parameters: {'max_depth': 3, 'min_samples_split': 19, 'min_samples_leaf': 2, 'n_estimators': 298, 'learning_rate': 0.5247506527045183}. Best is trial 44 with value: 0.5995101681778351.
[I 2026-09-28 13:55:43,527] Trial 73 finished with value: 0.5911105598299036 and parameters: {'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 4, 'n_estimators': 404, 'learning_rate': 0.4284228413257158}. Best is trial 44 with value: 0.5995101681778351.

Best parameters:
{'max_depth': 3, 'min_samples_split': 19, 'min_samples_leaf': 3, 'n_estimators': 463, 'learning_rate': 0.29437156675733234}

Best CV F1 score:
0.6008638991395335

In [72]:
# Get best parameters from Optuna
best_params = ada_study.best_params

# Build the best Decision Tree
best_tree = DecisionTreeClassifier(
    max_depth=best_params["max_depth"],
    min_samples_split=best_params["min_samples_split"],
    min_samples_leaf=best_params["min_samples_leaf"],
    random_state=42
)

# Build the best AdaBoost model
best_ada_optuna = AdaBoostClassifier(
    estimator=best_tree,
    n_estimators=best_params["n_estimators"],
    learning_rate=best_params["learning_rate"],
    random_state=42
)

# Train
best_ada_optuna.fit(X_train, y_train)

# Test prediction
y_pred_ada_optuna = best_ada_optuna.predict(X_test)

print("AdaBoost Test Classification Report:")
print(
    classification_report(
        y_test,
        y_pred_ada_optuna
    )
)

print("\nAdaBoost Confusion Matrix:")
print(
    confusion_matrix(
        y_test,
        y_pred_ada_optuna
    )
)

AdaBoost Test Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.89      0.86      1033
           1       0.63      0.52      0.57       374

    accuracy                           0.79      1407
   macro avg       0.73      0.71      0.72      1407
weighted avg       0.78      0.79      0.78      1407


AdaBoost Confusion Matrix:
[[916 117]
 [178 196]]

In [73]:
log_experiment(
    model_name="AdaBoost",
    approach="Optuna",
    y_true=y_test,
    y_pred=y_pred_ada_optuna,
    notes="AdaBoost parameters with Optuna"
)

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
1,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler
2,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max
3,DecisionTree,SMOTEENN,0.725657,0.489691,0.762032,0.596234,None,None,Decision Tree with smoteenn
4,RandomForest,SMOTEENN,0.718550,0.482026,0.788770,0.598377,None,None,Random Forest + SMOTEENN
5,XGBoost,Baseline,0.769723,0.572254,0.529412,0.550000,None,None,Default XGBoost parameters
6,XGBoost,SMOTEENN,0.732765,0.498305,0.786096,0.609959,None,None,XGBoost parameters with somte enn
7,XGBoost,smote,0.769723,0.565789,0.574866,0.570292,None,None,XGB post smote
8,XGBoost,ADASYN,0.763326,0.553247,0.569519,0.561265,None,None,XGBoost parameters with ADASYN
9,XGBoost,scale_pos_weight,0.747690,0.519115,0.689840,0.592423,None,None,XGBoost parameters with scale pos weight
10,AdaBoost,Sample Weighting,0.732054,0.497545,0.812834,0.617259,None,None,Default AdaBoost parameters
11,XGBoost,RandomizedSearchCV,0.728500,0.493528,0.815508,0.614919,None,None,XGBoost parameters with randomized search cv
12,RandomForest,Class Weight,0.718550,0.482258,0.799465,0.601610,None,None,Default Random Forest parameters
13,CatBoost,Class Weight,0.743426,0.511586,0.767380,0.613904,None,None,Default CatBoost parameters
14,LightGBM,scale_pos_weight,0.749112,0.519409,0.751337,0.614208,None,None,Default LightGBM parameters
15,XGBoost,Optuna,0.724236,0.488636,0.804813,0.608081,None,None,XGBoost parameters with optuna
16,AdaBoost,RandomizedSearchCV,0.786780,0.605714,0.566845,0.585635,None,None,AdaBoost parameters with Randomized Search CV
17,AdaBoost,Optuna,0.790334,0.626198,0.524064,0.570597,None,None,AdaBoost parameters with Optuna

In [74]:
joblib.dump(
    best_ada_optuna,
    'best_adaboost_churn_model.pkl'
)

print(
    "Best AdaBoost model successfully saved "
    "as 'best_adaboost_churn_model.pkl'"
)

Best AdaBoost model successfully saved as 'best_adaboost_churn_model.pkl'

In [76]:
results_df = pd.DataFrame(experiment_results)

# Sort by F1 score
results_df = results_df.sort_values(
    by="F1",
    ascending=False
).reset_index(drop=True)

# Display
display(results_df)

# Create timestamp
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

file_name = f"churn_experiment_results_{timestamp}.xlsx"

# Export
with pd.ExcelWriter(
    file_name,
    engine="openpyxl"
) as writer:

    results_df.to_excel(
        writer,
        sheet_name="Experiment Results",
        index=False
    )

print(f"Results exported to: {file_name}")

,Model,Approach,Accuracy,Precision,Recall,F1,CV_F1_Mean,Best_Params,Notes
0,AdaBoost,Sample Weighting,0.732054,0.497545,0.812834,0.617259,None,None,Default AdaBoost parameters
1,XGBoost,RandomizedSearchCV,0.728500,0.493528,0.815508,0.614919,None,None,XGBoost parameters with randomized search cv
2,LightGBM,scale_pos_weight,0.749112,0.519409,0.751337,0.614208,None,None,Default LightGBM parameters
3,CatBoost,Class Weight,0.743426,0.511586,0.767380,0.613904,None,None,Default CatBoost parameters
4,XGBoost,SMOTEENN,0.732765,0.498305,0.786096,0.609959,None,None,XGBoost parameters with somte enn
5,XGBoost,Optuna,0.724236,0.488636,0.804813,0.608081,None,None,XGBoost parameters with optuna
6,RandomForest,Class Weight,0.718550,0.482258,0.799465,0.601610,None,None,Default Random Forest parameters
7,RandomForest,SMOTEENN,0.718550,0.482026,0.788770,0.598377,None,None,Random Forest + SMOTEENN
8,DecisionTree,SMOTEENN,0.725657,0.489691,0.762032,0.596234,None,None,Decision Tree with smoteenn
9,XGBoost,scale_pos_weight,0.747690,0.519115,0.689840,0.592423,None,None,XGBoost parameters with scale pos weight
10,AdaBoost,RandomizedSearchCV,0.786780,0.605714,0.566845,0.585635,None,None,AdaBoost parameters with Randomized Search CV
11,AdaBoost,Optuna,0.790334,0.626198,0.524064,0.570597,None,None,AdaBoost parameters with Optuna
12,XGBoost,smote,0.769723,0.565789,0.574866,0.570292,None,None,XGB post smote
13,XGBoost,ADASYN,0.763326,0.553247,0.569519,0.561265,None,None,XGBoost parameters with ADASYN
14,XGBoost,Baseline,0.769723,0.572254,0.529412,0.550000,None,None,Default XGBoost parameters
15,DecisionTree,Baseline,0.765791,0.568750,0.486631,0.524496,None,None,Base line Decision Tree model
16,DecisionTree,MinMaxScaler,0.714996,0.466993,0.510695,0.487867,None,None,Decision Tree with Min Max
17,DecisionTree,StandardScaler,0.706468,0.452088,0.491979,0.471191,None,None,Decision Tree after Standard Scaler

Results exported to: churn_experiment_results_2026-09-28_14-03-46.xlsx